// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjUkvUe1-T0A-Sj4IWBOEca53SmGeGQXw',
    appId: '1:20173192546:web:b490836acbf429abe1803b',
    messagingSenderId: '20173192546',
    projectId: 'liftzy-faceyoga',
    authDomain: 'liftzy-faceyoga.firebaseapp.com',
    databaseURL: 'https://liftzy-faceyoga-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liftzy-faceyoga.firebasestorage.app',
    measurementId: 'G-5XLF0SJY90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGt9IvPsCW75bpeYbjIg_-UBgqaVwsBo0',
    appId: '1:20173192546:android:03b7f3b22706a316e1803b',
    messagingSenderId: '20173192546',
    projectId: 'liftzy-faceyoga',
    databaseURL: 'https://liftzy-faceyoga-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'liftzy-faceyoga.firebasestorage.app',
  );
}
